version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devsibre
      MYSQL_USER: devsibre_user
      MYSQL_PASSWORD: devsibre_pass
      TZ: America/Sao_Paulo
    ports:
      - "3309:3306"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak-app
    command: ["start-dev", "--import-realm", "--hostname-strict=false"]
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_FRAME_ANCESTORS: "'self' http://localhost:4200"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_PROXY: "edge"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    networks:
      - app-network

  # ⚠️ A API não está sendo executada via Docker neste momento.
  # Para rodá-la em container, seria necessário subir também o frontend no mesmo ambiente,
  # pois a autenticação com o Keycloak falha devido à diferença de origens (localhost vs container).
  # Isso ocorre por causa das restrições de CORS e do isolamento de rede entre o host e o Docker.
  devsibre-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: devsibre-api
    container_name: devsibre-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: devsibre
      DB_USERNAME: devsibre_user
      DB_PASSWORD: devsibre_pass
      KEYCLOAK_URL: http://keycloak-app:8080
      KEYCLOAK_REALM: sibre
      KEYCLOAK_CLIENT_ID: devsibre-admin-api
      KEYCLOAK_CLIENT_SECRET: M2G1qggGOW1SLKTu2PMVLAwN6iEOxPRZ
      KEYCLOAK_ISSUER_URI: http://keycloak-app:8080/realms/sibre
      KEYCLOAK_JWKS_URI: http://keycloak-app:8080/realms/sibre/protocol/openid-connect/certs
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - mysql-db
      - keycloak
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
